# Site settings
title: Pastries
description: The best Puerto Rican sweets
keywords: Professsional,Presentation,Baker
author: Sara's Quesitos LLC
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://sarasquesitos.com
sass:
    sass_dir: _sass
    style: compact
